name: Feature Build and Analyze

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
    runs-on:
      group: Default

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build data
        id: build-data
        run: |
          echo "current_branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Github CLI
        uses: wusatosi/setup-gh@v1

      - name: Versioning
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUR_VERSION: ${{ vars.CURRENT_VERSION }}
        run: |
          NEW_VERSION=$(./gradlew properties -q | awk '/^version:/ {print $2}')
          echo "NEW VERSION: $NEW_VERSION"
          gh variable set CURRENT_VERSION --body $NEW_VERSION
