name: Feature Build and Analyze

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
    runs-on:
      group: Default

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build data
        id: build-data
        run: |
          echo "current_branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: ./gradlew test

      - name: Generate Reports
        run: ./gradlew koverVerify koverHtmlReport koverXmlReport

      - name: Quality Gate
        env:
          THOMAS_CORE_SONAR_LOGIN: ${{ secrets.CORE_SONAR_LOGIN }}
          THOMAS_SONAR_URL: ${{ secrets.SONAR_URL }}
        run: |
          echo "THOMAS_CORE_SONAR_LOGIN: $THOMAS_CORE_SONAR_LOGIN"
          echo "THOMAS_SONAR_URL: $THOMAS_SONAR_URL"
          ./gradlew sonar

      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: develop
          title: Pull Request from branch ${{ steps.build-data.outputs.current_branch }} to develop
