name: Feature Build and Analyze

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
    runs-on:
      group: Default

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build data
        id: build-data
        run: |
          echo "current_branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Versioning
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUR_VERSION: ${{ vars.CURRENT_VERSION }}
        run: |
          NEW_VERSION=$(./gradlew properties -q | awk '/^version:/ {print $2}')
          echo "NEW VERSION: $NEW_VERSION"
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/project-thomas/thomas-core/actions/variables/CURRENT_VERSION \
            -d '{"name":"CURRENT_VERSION","value":$NEW_VERSION}'

